language: node_js
node_js:
  - "8.5.0"
before_install: npm install -g grunt-cli
install: npm install
sudo: false
cache:
  directories:
    - node_modules
script: npm run test
after_success:
  - npm run coverage --force
  - bash <(curl -s https://codecov.io/bash)
